export const ROUTE_PATHS = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/admin',
  LEGACY_DASHBOARD: '/dashboard',
  ADMIN_INFO: '/admin-info',
  TENANTS: '/admin/tenants',
  DEPARTMENTS: '/admin/departments',
  USERS: '/admin/users',
  ROLES: '/admin/roles',
  USER_TENANT_ROLES: '/admin/user-tenant-roles',
  USER_CAREER_RANKS: '/admin/career-ranks',
  USER_ROLE_CONTEXTS: '/admin/role-contexts',
  REPORTS: '/admin/reports',
  SETTINGS: '/admin/settings',
} as const;